- name: Install createlinks script
  copy: src=createlinks dest=/usr/local/bin/createlinks owner=root group=root mode=0755

- name: Install systemd timers
  copy: src={{ item }} dest=/etc/systemd/system/{{ item }} owner=root group=root mode=0644
  with_items:
    - createlinks.timer
    - createlinks.service

- name: Activate systemd timers
  service: name={{ item }} enabled=yes state=started
  with_items:
    - createlinks.timer
