- name: Configure pacman mirror
  copy:
    src: mirrorlist
    dest: /etc/pacman.d/mirrorlist
    owner: root
    group: root
    mode: 0644

- name: Update package cache
  pacman:
    update_cache: yes

- name: Install essential tools
  pacman:
    name: vim,nano,tmux,htop,ncdu,rsync,vnstat
    state: present

- name: Start and enable vnstatd
  service:
    name: vnstat
    enabled: yes
    state: started

- name: Start and enable auditd
  service:
    name: auditd
    enabled: yes
    state: started

- name: Start and enable systemd-timesyncd
  service:
    name: systemd-timesyncd
    enabled: yes
    state: started
