- name: Full system upgrade (equivalent to `pacman -Syu`)
  pacman:
    update_cache: yes
    upgrade: yes
    extra_args: --noconfirm

- name: Install essential tools
  pacman:
    name: vim,nano,tmux,htop,ncdu,rsync,vnstat
    state: present

- name: Start and enable vnstatd
  service:
    name: vnstat
    enabled: yes
    state: started

- name: Start and enable auditd
  service:
    name: auditd
    enabled: yes
    state: started

- name: Start and enable systemd-timesyncd
  service:
    name: systemd-timesyncd
    enabled: yes
    state: started
