- name: Install devtools
  pacman:
    name: git,base-devel,devtools,pyalpm
    state: present

- name: Ensure destination directory exists
  file:
    path: "{{ dest_dir}}"
    state: directory
    owner: arch
    group: arch
    mode: 0755
  check_mode: no

- name: Copy scripts
  synchronize:
    src:  "{{ src_dir }}"
    dest: "{{ dest_dir }}"
    rsync_opts: "-avz --delete"
