- name: Deploy web server
  hosts: web
  become: true
  vars:
    app_user: http
    app_group: http
    nginx_server_name: loongarchlinux.lcpu.dev
    src_dir: "../../web_server/"
    dest_dir: "/srv/http/status"
  roles:
    - common
    - nginx
    - syncweb
